name: "PlantUML Processing Action"
description: "A GitHub Action to process .src.md files and convert them to .md files with embedded PlantUML diagrams."
author: "Kfir Yehezkel"
branding:
  icon: 'file-text'
  color: 'blue'

inputs:
  output_dir:
    description: "The output directory where the .md files will be saved."
    required: true
    default: "mdcompile"
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.output_dir }}    

