name: Test Action

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.9'

      - name: Create test files
        run: |
          # Create test directory
          mkdir test_files
          
          # Create a sample .codemd file for testing
          echo -e 'This is a test.\n\n```plantuml\nAlice -> Bob: Hello\n```' > test_files/test.src.md

      - name: Run Action Locally
        uses: ./  # Points to the root of the action repository
        with:
          output_dir: "test_files"

      - name: List files in test_output directory
        run: ls -la ./test_files

      - name: Verify output
        run: |
          # Check if the output file was created
          if [ ! -f "./test_files/test.md" ]; then
            echo "Test failed: output file not created."
            exit 1
          fi

          # Check the contents of the generated Markdown file
          grep -q "![Diagram 1]" ./test_files/test.md || (echo "Test failed: SVG link not found." && exit 1)

      - name: Clean up
        run: |
          rm -rf test_files test_output
